# Docker overrides
# General configuration
config.dir.path=config

# Database configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/lrharvester
spring.datasource.username=lrharvester
spring.datasource.password=lrharvester

solr.host=http://solr:8983/solr

# Embedding model configuration
embedding.api.url=http://localhost:8989/api/v1/embeddings
embedding.model.name=e8a730bb-e48f-4cd8-94c4-4f2be2530d8f
embedding.model.dimension=1024
embedding.api.timeout.seconds=60
# The maximum size of the segment, defined in tokens.
embedding.max.segment.size.tokens=128
# The maximum overlap between adjacent generated chunks/segments, defined in tokens.
# Must be less than or equal to embedding.max.segment.size.tokens.
embedding.max.overlap.size.tokens=0
# The maximum number of chunks to generate for a document. If the document is too large, it will be truncated to fit this limit.
embedding.max.chunks.size=5
# OpenAI API key for embedding model (if using OpenAI) or other API key if required by the embedding service.
#embedding.api.key=
#embedding.model.datatype=float
